OperationsCenter:
  HostName: @ROUTE_53_DOMAIN@
  #https://support.cloudbees.com/hc/en-us/articles/360058867672 
  Platform: "aws"
  CasC:
    Enabled: true
  ExtraVolumes:
  - name: mc-casc-bundle
    configMap:
      name: mc-casc-bundle
  - name: login
    secret:
      secretName: login
  ExtraVolumeMounts:
  - name: mc-casc-bundle
    mountPath: /var/jenkins_home/jcasc-bundles-store/mc
    readOnly: true
  - name: login
    mountPath: /var/login
    readOnly: true
Hibernation:
  Enabled: true
