repositories:
- name: cloudbees
  url:  https://charts.cloudbees.com/public/cloudbees
helmDefaults:
  wait: true
  timeout: 1200
  recreatePods: false
  historyMax: 0
  createNamespace: true
  cleanupOnFail: true
releases:
# https://docs.cloudbees.com/docs/cloudbees-ci/latest/casc-controller/
- name: casc
  namespace: cbci
  chart: {{ requiredEnv "HELM_DIR" }}/casc
  values:
  - domain: @ROUTE_53_DOMAIN@
  - mcCount: @MC_COUNT@
# https://artifacthub.io/packages/helm/cloudbees/cloudbees-core
- name: cbci
  namespace: cbci
  chart: cloudbees/cloudbees-core
  version: "@CB_CI_VERSION@"
  values:
  - /tmp/cbci-temp.yaml


