image:
  repository: ghcr.io/jglick/velero
  tag: concurrent-snapshot
  pullPolicy: Always
initContainers:
- name: velero-plugin-for-aws
  image: ghcr.io/jglick/velero-plugin-for-aws:x-region
  imagePullPolicy: Always
  volumeMounts:
  - mountPath: /target
    name: plugins
- name: inject-metadata-velero-plugin
  image: ghcr.io/cloudbees-oss/inject-metadata-velero-plugin:main
  imagePullPolicy: Always
  volumeMounts:
  - mountPath: /target
    name: plugins
configuration:
  provider: aws
  backupStorageLocation:
    bucket: @NAME@
    config:
      region: @WEST_REGION@
  volumeSnapshotLocation:
    config:
      region: @REGION@
      altRegion: @WEST_REGION@
  extraEnvVars:
    AWS_CLUSTER_NAME: @NAME@-@REGION@
    VELERO_AWS_AZ_OVERRIDE: @ZONE@
serviceAccount:
  server:
    create: false
    name: velero
credentials:
  useSecret: false